- hosts: lamp
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  become: yes
  roles:
  - python
  - nginx
  - mysql
  - php
  - wordpress
